# Generated by Django 3.0.5 on 2020-04-05 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Study name')),
                ('main_purpose', models.CharField(max_length=100, verbose_name='Main purpose')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quick_descritpion', models.TextField(blank=True, max_length=500, verbose_name='Quick description')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('rate', models.IntegerField(blank=0, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Evaluation')),
                ('commentary', models.TextField(blank=True, verbose_name='Commentary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstbook.Study')),
            ],
        ),
    ]
