# Generated by Django 3.0.5 on 2020-04-05 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='cake',
            new_name='study',
        ),
    ]
