# Generated by Django 3.0.5 on 2020-04-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pathology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=100, verbose_name='Patient Anonymisation')),
                ('birth_date', models.DateField(verbose_name='Date of birth')),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=20, verbose_name='Gender')),
                ('size', models.IntegerField(help_text='(cm)', verbose_name='Size')),
                ('weight', models.IntegerField(help_text='(kg)', verbose_name='Weight')),
                ('pathologies', models.ManyToManyField(to='inclusions.Pathology')),
            ],
        ),
    ]
