# Generated by Django 3.0.5 on 2020-04-09 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inclusions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='pathology',
            name='organ',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inclusions.Organ'),
        ),
    ]
